### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by pankochicken** [arthurgarzajr/MMM-DailyBibleVerse#1]
@arthurgarzajr  Love the idea of this module! Git pull was no issue, but had an issue with the npm install. Where did I go wrong? Thanks!

pi@raspberrypi:~/MagicMirror/modules/MMM-DailyBibleVerse $ npm install
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/node_modules/node_helper/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

**Comment by arthurgarzajr** [comment]
Hi pankochicken, I should not have placed the npm install instructions to setup the dailybibleverse module because it is not needed. All you need to do is pull down the git repo and place it in the appropriate directory. Disregard the npm install. 

Please let me know if it works for you and thanks for using the module!

**Comment by pankochicken** [comment]
Gotcha, thank you!! Works great. One more question: if I wanted to change the font and the size of the font of the verse, how would I go about doing that?
